plugins { id 'com.android.application' }

android {
    namespace 'com.riopintocoach.app'
    compileSdk 35

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId 'com.riopintocoach.app'
        minSdk 26
        targetSdk 35
        versionCode 54400
        versionName '5.4.400'
    }
}


dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
}
